### ISSUE TITLE
Fails to build on node 4.1.0

### ISSUE THREAD

**Issue by aaronjensen** [tblobaum/rconsole#13]
```
> rconsole@0.2.0 install /home/vagrant/.cid/hotel-api/node_modules/rconsole
> node-gyp rebuild

make: Entering directory `/home/vagrant/.cid/hotel-api/node_modules/rconsole/build'
  CXX(target) Release/obj.target/syslog/src/syslog.o
../src/syslog.cc:35:41: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 static v8::Handle<v8::Value> open(const v8::Arguments& args) {
                                         ^
../src/syslog.cc:35:56: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 static v8::Handle<v8::Value> open(const v8::Arguments& args) {
                                                        ^
../src/syslog.cc: In function ‘v8::Handle<v8::Value> open(const int&)’:
../src/syslog.cc:36:9: error: invalid types ‘const int[int]’ for array subscript
   args[0]->ToString()->WriteAscii((char*) &title);
         ^
../src/syslog.cc:37:24: error: invalid types ‘const int[int]’ for array subscript
   int facility = args[1]->ToInteger()->Int32Value();
                        ^
../src/syslog.cc:38:24: error: invalid types ‘const int[int]’ for array subscript
   int log_upto = args[2]->ToInteger()->Int32Value();
                        ^
../src/syslog.cc:42:10: error: ‘New’ is not a member of ‘v8::String’
   return String::New("true");
          ^
../src/syslog.cc: At global scope:
../src/syslog.cc:45:41: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 static v8::Handle<v8::Value> exit(const v8::Arguments& args) {
                                         ^
../src/syslog.cc:45:56: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 static v8::Handle<v8::Value> exit(const v8::Arguments& args) {
                                                        ^
../src/syslog.cc: In function ‘v8::Handle<v8::Value> exit(const int&)’:
../src/syslog.cc:48:10: error: ‘New’ is not a member of ‘v8::String’
   return String::New("true");
          ^
../src/syslog.cc: At global scope:
../src/syslog.cc:51:40: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 static v8::Handle<v8::Value> log(const v8::Arguments& args) {
                                        ^
../src/syslog.cc:51:55: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 static v8::Handle<v8::Value> log(const v8::Arguments& args) {
                                                       ^
../src/syslog.cc: In function ‘v8::Handle<v8::Value> log(const int&)’:
../src/syslog.cc:52:24: error: invalid types ‘const int[int]’ for array subscript
   int severity = args[0]->ToInteger()->Int32Value();
                        ^
../src/syslog.cc:53:39: error: invalid types ‘const int[int]’ for array subscript
   v8::String::Utf8Value message(args[1]->ToString());
                                       ^
../src/syslog.cc:56:10: error: ‘New’ is not a member of ‘v8::String’
   return String::New("true");
          ^
../src/syslog.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/syslog.cc:60:39: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [5], v8::Handle<v8::Value> (&)(const int&))’
   NODE_SET_METHOD(target, "open", open);
                                       ^
../src/syslog.cc:60:39: note: candidate is:
In file included from ../src/syslog.cc:25:0:
/home/vagrant/.node-gyp/4.1.0/include/node/node.h:236:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/vagrant/.node-gyp/4.1.0/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
../src/syslog.cc:60:39: note:   cannot convert ‘open’ (type ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
   NODE_SET_METHOD(target, "open", open);
                                       ^
../src/syslog.cc:61:39: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [5], <unresolved overloaded function type>)’
   NODE_SET_METHOD(target, "exit", exit);
                                       ^
../src/syslog.cc:61:39: note: candidate is:
In file included from ../src/syslog.cc:25:0:
/home/vagrant/.node-gyp/4.1.0/include/node/node.h:236:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/vagrant/.node-gyp/4.1.0/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
../src/syslog.cc:61:39: note:   cannot convert ‘exit’ (type ‘<unresolved overloaded function type>’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
   NODE_SET_METHOD(target, "exit", exit);
                                       ^
../src/syslog.cc:62:37: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [4], v8::Handle<v8::Value> (&)(const int&))’
   NODE_SET_METHOD(target, "log", log);
                                     ^
../src/syslog.cc:62:37: note: candidate is:
In file included from ../src/syslog.cc:25:0:
/home/vagrant/.node-gyp/4.1.0/include/node/node.h:236:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/vagrant/.node-gyp/4.1.0/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
../src/syslog.cc:62:37: note:   cannot convert ‘log’ (type ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
   NODE_SET_METHOD(target, "log", log);
                                     ^
../src/syslog.cc: At global scope:
../src/syslog.cc:45:30: warning: ‘v8::Handle<v8::Value> exit(const int&)’ defined but not used [-Wunused-function]
 static v8::Handle<v8::Value> exit(const v8::Arguments& args) {
                              ^
make: *** [Release/obj.target/syslog/src/syslog.o] Error 1
make: Leaving directory `/home/vagrant/.cid/hotel-api/node_modules/rconsole/build'
gyp ERR! build error
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.cid/hotel-api/node_modules/rconsole
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by tblobaum** [comment]
Does it work with an earlier node version?

**Comment by aaronjensen** [comment]
looks like what you have on master will work if you publish it.

**Comment by aaronjensen** [comment]
Looks like it doesn't actually build on ubuntu:

```
[17:11:13][npm install] In file included from ../src/syslog.cc:24:0:
[17:11:13][npm install] /home/deploy/.node-gyp/4.1.0/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
[17:11:13][npm install] /home/deploy/.node-gyp/4.1.0/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
[17:11:13][npm install] /home/deploy/.node-gyp/4.1.0/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
[17:11:13][npm install] ../src/syslog.cc:65:15: error: variable or field ‘init’ declared void
[17:11:13][npm install] ../src/syslog.cc:65:11: error: ‘Handle’ is not a member of ‘v8’
[17:11:13][npm install] ../src/syslog.cc:65:32: error: expected primary-expression before ‘>’ token
[17:11:13][npm install] ../src/syslog.cc:65:34: error: ‘target’ was not declared in this scope
[17:11:13][npm install] ../src/syslog.cc:71:1: error: ‘init’ was not declared in this scope
```

**Comment by aaronjensen** [comment]
After further digging, my ubuntu issues was a lack of gcc 4.7 on precise. Now it builds properly, please release a new version when you get a chance.
